package org.knowm.xchange.bitget.uta.v3.service;

import org.knowm.xchange.service.trade.params.orders.OrderQueryParams;

/**
 * Order query parameters for the UTA v3 order-info endpoint.
 *
 * <p>{@code orderId} takes priority when both are supplied (the endpoint ignores {@code clientOid}
 * then). {@code clientOid} is the idempotency key generated by {@link
 * BitgetUtaV3TradeServiceRaw} on placement (or the caller's user reference echoed back), so a
 * caller reconciling an ambiguous placement can look the order up by client reference alone — the
 * path the {@link BitgetUtaV3UnknownOutcomeException} contract points at.
 */
public class BitgetUtaV3OrderQueryParams implements OrderQueryParams {

  private String orderId;
  private String clientOid;

  public BitgetUtaV3OrderQueryParams() {}

  public BitgetUtaV3OrderQueryParams(String orderId) {
    this.orderId = orderId;
  }

  @Override
  public String getOrderId() {
    return orderId;
  }

  @Override
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getClientOid() {
    return clientOid;
  }

  public void setClientOid(String clientOid) {
    this.clientOid = clientOid;
  }
}
