package info.bitrich.xchangestream.bitget.uta.v3.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;
import lombok.Builder;
import lombok.Data;
import lombok.extern.jackson.Jacksonized;

/**
 * Bitget UTA v3 public trade push payload ({@code {i, L, p, v, S, T, isRPI}}).
 *
 * @since 5.1.0
 */
@Data
@Builder
@Jacksonized
public class BitgetUtaV3PublicTradeData {

  /** Fill execution id. */
  @JsonProperty("i")
  private String id;

  /** Execution correlation id. */
  @JsonProperty("L")
  private String executionCorrelationId;

  @JsonProperty("p")
  private BigDecimal price;

  @JsonProperty("v")
  private BigDecimal volume;

  /** {@code buy} or {@code sell}. */
  @JsonProperty("S")
  private String side;

  /** Trade timestamp, epoch milliseconds. */
  @JsonProperty("T")
  private Long timestamp;

  /** Whether the trade was generated by the RP (liquidity) engine: {@code yes} or {@code no}. */
  @JsonProperty("isRPI")
  private String isRPI;
}
